name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building the application..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: python:3.9-slim
    steps:
      - name: Deploy
        run: echo "Deploying the application..."

      # 👉 insérer ici la logique de déploiement

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify team
        run: echo "Notifying the team..."

      # 👉 insérer ici la logique de notification
